//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomScheduleMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleID { get; set; }
        public Nullable<int> DayID { get; set; }
        public Nullable<int> AuditoryID { get; set; }
        public Nullable<int> PairID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> GroupID { get; set; }
    
        public virtual Auditory Auditory { get; set; }
        public virtual Day Day { get; set; }
        public virtual Group Group { get; set; }
        public virtual Pair Pair { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
